config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/about_me', to: "static_pages#about_me", as: "about_me"
  get 'admin', to: 'static_pages#admin', as: 'admin'

  devise_for :users, path: '', path_names:{sign_in: 'login', sign_out:'logout', sign_up: 'register' }
  resources :states
  resources :countries
  resources :blogs


  root to: "static_pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :state
  has_one :country, through: :state

  mount_uploader :main_photo, BlogUploader
  mount_uploader :photo_one, BlogUploader
  mount_uploader :photo_two, BlogUploader
  mount_uploader :photo_three, BlogUploader
  mount_uploader :photo_four, BlogUploader
  mount_uploader :photo_five, BlogUploader
  mount_uploader :photo_six, BlogUploader
  mount_uploader :photo_seven, BlogUploader
  mount_uploader :photo_eight, BlogUploader
  mount_uploader :photo_nine, BlogUploader
  mount_uploader :photo_ten, BlogUploader


end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states
  has_many :blogs, through: :states

  def self.asc_order
    order('name ASC')
  end

end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  access all: [:show, :index], user: :all
  layout 'blog'

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)
    
    if @blog.save
      redirect_to @blog, notice: 'Your post is live'
    else
      render :new
     end
    end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: "You have updated your blogs post"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path

  end

  private

  def blog_params
    params.require(:blog).permit(:title,
                                 :body,
                                 :state_id, 
                                 :country,
                                 :main_photo, 
                                 :photo_one,
                                 :photo_two,
                                 :photo_three,
                                 :photo_four,
                                 :photo_five,
                                 :photo_six,
                                 :photo_seven,
                                 :photo_eight,
                                 :photo_nine,
                                 :photo_ten)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
before_action :set_country, only: [:show,:edit,:update,:destroy]
access all: [:show, :index], user: :all
layout 'blog'

  def index
    @countries = Country.asc_order
  end

  def edit
    @country = Country.find(params[:id])
  end

  def create
    @country = Country.new(country_params)
    if @country.save
      redirect_to @country, notice: "You've created a new country"
    else
      render :new
    end
  end

  def new
    @country = Country.new
  end

  def show
  end

  def update 
    if @country.update(country_params)
      redirect_to @country, notice: "You're country has been updated"
    else
      render :edit
    end
  end

  def destroy
    @country.destroy
    redirect_to admin_path
  end

  private

  def set_country
    @country = Country.find(params[:id])
  end

  def country_params
    params.require(:country).permit(:name)
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show,:edit,:update,:destroy]
  access all: [:show, :index], user: :all
  layout "blog"

  def index
    @states = State.all
  end

  def new
    @state = State.new
  end

  def create
    @state = State.new(state_params)
    
    if @state.save
      redirect_to @state, notice: "You've created a state"
    else
      render :new
    end
  end

  def show

  end

  def edit

  end

  def update
    if @state.update(state_params)
      redirect_to @state
    else
      render :edit
    end
  end

  def destroy
    @state.destroy
    redirect_to states_path
  end

  private

  def set_state
    @state = State.find(params[:id])
  end

  def state_params
    params.require(:state).permit(:name, :country_id)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  access all: [:home, :about_me], user: :all
  def home
    @blog = Blog.order("RANDOM()").limit(1)
  end

  def about_me
  end

  def admin
    @countries = Country.order('name ASC')
    @states = State.all
    @blogs = Blog.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper

end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
  <div class="card">
    <form>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.text_field :title, class: "form-control", placeholder: "title" %>
          </div>

          <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, class: "form-control", rows: 10 %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group country_state_select">  

            <%= f.collection_select(:state_id, State.all, :id, :name, {
                                    include_blank: true
                                    },class: "form-control"  )%>
            <%= f.label :state_id %>
          </div>
        <div class="form-group">
          <h5>Thumb Imagine:</h5>  
              <%= f.file_field :main_photo%>
          </div>
          <div class="form-group">
            <h6>Photo One:</h6>
              <%= f.file_field :photo_one %>
            <h6>Photo Two: </h6>
              <%= f.file_field :photo_two %>
            <h6>Photo Three: </h6>
              <%= f.file_field :photo_three %>
            <h6>Photo Four: </h6>
              <%= f.file_field :photo_ten %>        
            <h6>Photo Five:</h6>
              <%= f.file_field :photo_four %>
            <h6>Photo Six:</h6>
              <%= f.file_field :photo_five %>
            <h6>Photo Seven: </h6>
              <%= f.file_field :photo_six %>
            <h6>Photo Eight: </h6>
              <%= f.file_field :photo_seven %>
            <h6>Photo Nine </h6>
              <%= f.file_field :photo_eight %>
            <h6>Photo Ten: </h6>
              <%= f.file_field :photo_nine %>
          </div>  
        </div>
        <div class="row">

          <div class="save-button">
            <%= f.submit "Save", class: 'form-control' %>
            <% end %> 
          </div>
      </div>
  </form>
</div>

app/views/blogs/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>

<h1>Edit your post</h1>
<%= render 'form', blog: @blog %>

</body>
</html>

app/views/blogs/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Index Page</title>
</head>
<body>
  <div class="container">
  <% @blogs.each do |blog| %>
    <div class="card" style="width: 20rem;">
      <%= image_tag blog.main_photo %>
      <div class="card-body">
        <h5 class="card-title"><%=link_to blog.title, blog_path(blog) %></h5>
        <p class="card-text"><%= blog.body %></p>
        <%= link_to 'Edit', edit_blog_path(blog) if logged_in?(:user)  %>
        
      </div>
    </div>
  

  <% end %>
</div>
</body>
</html>

app/views/blogs/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<h1>Make a new post!</h1>
<%= render 'form', blog: @blog %>
</body>
</html>

app/views/blogs/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <div class="card" style="width: 18rem;">
  <%= image_tag @blog.main_photo %>
  <div class="card-body">
    <h5 class="card-title"><%= @blog.title %></h5>
    <p class="card-text"><%= @blog.body %></p>
    <%if logged_in?(:user) %>
    <%= link_to 'Delete', blog_path(@blog), method: :delete, data: { confirm: "Are you sure you want to remove this?"} %>
    <%= link_to 'Edit', edit_blog_path(@blog) %>
    <% end %>
  </div>
</div>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag @blog.photo_one unless @blog.photo_one.blank? %>
    </div>
    <div class="carousel-item">
      <%= image_tag @blog.photo_two unless @blog.photo_two.blank? %>
    </div>
    <div class="carousel-item">
      <%= image_tag @blog.photo_three unless @blog.photo_three.blank? %>
    </div>
        <div class="carousel-item">
      <%= image_tag @blog.photo_four unless @blog.photo_four.blank? %>
    </div>
        <div class="carousel-item">
      <%= image_tag @blog.photo_five unless @blog.photo_five.blank? %>
    </div>
        <div class="carousel-item">
      <%= image_tag @blog.photo_six unless @blog.photo_six.blank? %>
    </div>
        <div class="carousel-item">
      <%= image_tag @blog.photo_seven unless @blog.photo_seven.blank? %>
    </div>
        <div class="carousel-item">
      <%= image_tag @blog.photo_eight unless @blog.photo_eight.blank? %>
    </div>
        <div class="carousel-item">
      <%= image_tag @blog.photo_nine unless @blog.photo_nine.blank? %>
    </div>
        <div class="carousel-item">
      <%= image_tag @blog.photo_ten unless @blog.photo_ten.blank? %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</body>
</html>

app/views/countries/_country_form.html.erb
<% form_for @country do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/countries/_form.html.erb
<%= form_for @country do |f| %>
  <div class="card country_card">
    <form>
      <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
        </div>
    </form>
  </div>
<% end %>

app/views/countries/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <div class="container">
    <h1>Edit Country</h1>

    <%= render 'form' %>
  </div>
</body>
</html>

app/views/countries/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <div class="container">
    <h1>Countries</h1>
      <% @countries.each do |country| %>
      <div class="card" style="width: 20rem;">
          <div class="card-body">
            <div class="row">
            <div class="col-lg-6">
            <%= link_to country.name, country_path(country) %>
          </div>
          <div class="col-md-6">
            <% if logged_in?(:user) %>
            <%= link_to "Edit", edit_country_path(country) %>
            <%= link_to "Destroy", country, method: :delete, data: { confirm: "Are you sure you want to delete this state?"} %>
            <% end %>
          </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <h6>States:</h6>
            <% country.states.each do |state| %>
            <%= link_to state.name, controller: 'states', action: "show", id:state  %>
          </div>
        </div>
            <% end %>
      </div>
</div>
</body>
</html>




        <% end %>

app/views/countries/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <div class="container">
    <h1>New Country</h1>

    <%= render 'form' %>
  </div>
</body>
</html>

app/views/countries/show.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Show</title>
    </head>
    <body>
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <h5 class="card-title"><%= @country.name %></h5>
              <h3>States</h3>
            </div>
            <div class="card-title col-md-6">
              <% if logged_in?(:user) %>
              <%= link_to 'Edit', edit_country_path(@country) %>
              <%= link_to "Delete", @state, method: :delete, data: { confirm: "Are you sure you want to delete this state?"} %>
              <% end %>
            </div>
          </div>
          <% @country.states.each do |state| %>
          <h3>States</h3>
            <p class="card-text"><%=link_to state.name, state_path(state)  %></p>
          <% end %>
        </div>
      </div>
    </body>
  </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugbites</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav_bar" %>
    <div id="background"></div>
    <%= yield %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugbites</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="background"></div>
    <%= render "shared/nav_bar" %>
    <%= yield %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-dark bg-dark bg-light justify-content-center">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Home", root_path %>
        <%= link_to "About Me", about_me_path %>
        <%= link_to "Countries", countries_path %>
        <%= link_to "States", states_path %>
        <%= link_to "Blogs", blogs_path %>
        <%= link_to "Admin Page", admin_path if logged_in?(:user) %>
      </li>
    </ul>
  </div>
</nav>

app/views/states/_form.html.erb
<%= form_for @state do |f| %>
  <div class="card">
    <form>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.collection_select(:country_id, Country.all, :id, :name) %>
        <%= f.submit %>
      </div>
    </form>
  </div>
<% end %>

app/views/states/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <div class="container">
    <h1>Edit State</h1>

    <%= render 'form' %>
  </div>
</body>
</html>

app/views/states/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <div class="container">
    <h1>States</h1>
      <% @states.each do |state| %>
      <div class="card" style="width: 20rem;">
          <div class="card-body">
            <div class="row">
            <div class="col-lg-6">
            <%= link_to state.name, state_path(state) %>
          </div>
          <div class="col-md-6">
            <% if logged_in?(:user) %>
            <%= link_to "Edit", edit_state_path(state) %>
            <%= link_to "Destroy", state, method: :delete, data: { confirm: "Are you sure you want to delete this state?"} %>
            <% end %>
          </div>
          </div>
        </div>
      </div>
            <% end %>
</div>
</body>
</html>

app/views/states/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <div class="container">
    <h1>State</h1>

    <%= render 'form' %>
  </div>
</body>
</html>

app/views/states/show.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Show</title>
    </head>
    <body>
      <div class="card show_card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <h5 class="card-title"><%= @state.name %></h5>
            </div>
            <div class="card-title col-md-6">
              <% if logged_in?(:user) %>
              <%= link_to 'Edit', edit_state_path(@state) %>
              <%= link_to "Delete", @state, method: :delete, data: { confirm: "Are you sure you want to delete this state?"} %>
              <% end %>
            </div>
          </div>
          <% @state.blogs.each do |blog| %>
          <h3>Blog Titles:</h3>
            <p class="card-text"><%=link_to blog.title, blog_path(blog)  %></p>
          <% end %>
        </div>
      </div>
    </body>
  </html>












  

app/views/static_pages/about_me.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>About Me</title>
</head>
<body>
<div class="container">
  <div class="card text-center about-me-card">
    <div class="card-header">
      <h3>About Me, Bitches</h3>
    </div>
    <p>Bug bites and bruises was born on a sailing trip in the British Virgin Islands. My husband had taken up sailing with the idea that we might retire on a sailboat. I took just enough classes to be his first mate and know how to save him if the man went overboard and wasn’t entirely sure I would like living on a boat. I’m clumsy on my best days on solid ground and by day 2 or 3 (days flow by without notice when on a boat), I looked at my battered mosquito-eaten body and exclaimed “If we ever have a sailboat it must be named Bug Bights and Bruises!” If you’ve spent time in a marina you will know that like hair salons, the cheesier the pun in the name the better. And if you’ve spent time on a boat you’ll know that the bight is the turn in the line or a curve of the coast line. Sea punny! We still don’t have a sailboat, but we started this blog to chronicle our travels and share any tips, tricks, or wonderful experiences we have had.</p>
  </div>
</div>
</body>
</html>

app/views/static_pages/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>

  <div class="container">
    <div class="row">
      <div class="col-lg-3 admin_link">
        <div class="card">
          <h1>Countries</h1>
            <div class="card-body">
              <% @countries.each do |country| %>
                <div class="row">
                  <%= link_to country.name, country_path(country) %> 
                  <%= link_to "Edit", edit_country_path(country) %>
                  <%= link_to "Destroy", country, method: :delete, data: { confirm: "Are you sure you want to trump(destroy) this country?"} %>
                </div>
              <% end %>
            </div>
          </div>
          <%= link_to 'New country', new_country_path %>
        </div>

    <div class="col-lg-3 admin_link">
      <div class="card">
        <h1>States</h1>
          <div class="card-body">
            <% @states.each do |state| %>
              <div class="row">
                <%=link_to  state.name, state_path(state)  %>
                <%= link_to "Edit", edit_state_path(state) %>
                <%= link_to "Destroy", state, method: :delete, data: { confirm: "Are you sure you want to delete this state?"} %>                
              </div>
            <% end %>
          </div>
        </div>
            <%= link_to 'New State', new_state_path %>
      </div>

    <div class="col-lg-6 admin_link">
      <div class="card blogs-card">
        <h1>Blogs</h1>
          <div class="card-body">
            <% @blogs.each do |blog| %>
              <div class="row">
                <%=link_to blog.title, blog_path(blog)  %>
                <%= link_to "Edit", edit_blog_path(blog) %>
                <%= link_to "Destroy", blog, method: :delete, data: { confirm: "Are you sure you want to destroy this blog?"} %>
              </div>
            <% end %>
          </div>
        </div>
  <%= link_to 'New Blog', new_blog_path %>
      </div>
  </div>
</div>
</body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Home Page</title>
</head>
<body>
  <div class="container">
  <% @blog.each do |blog| %>
    <div class="card" style="width: 20rem;">
      <%= image_tag blog.main_photo %>
      <div class="card-body">
        <h5 class="card-title"><%=link_to blog.title, blog_path(blog) %></h5>
        <p class="card-text"><%= blog.body %></p>
        
      </div>
    </div>
  

  <% end %>
</div>
</body>
</html>